# Generated by Django 4.1.3 on 2022-11-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background',
            field=models.ImageField(blank=True, upload_to='media/board_images'),
        ),
    ]
