# Generated by Django 4.1.3 on 2022-11-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_background_column_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background',
            field=models.ImageField(blank=True, upload_to='background'),
        ),
    ]
