# Generated by Django 4.1.3 on 2022-11-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_alter_mark_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='color',
            field=models.CharField(default='#000', max_length=7),
        ),
    ]
