# Generated by Django 4.1.3 on 2022-11-27 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_alter_mark_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.RemoveField(
            model_name='card',
            name='file',
        ),
        migrations.AlterField(
            model_name='card',
            name='date_of_end',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='card_files/')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='boards.card')),
            ],
        ),
    ]
