# Generated by Django 4.1.3 on 2022-11-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_alter_card_options_remove_card_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_of_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
