# Generated by Django 4.1.3 on 2022-11-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_board_is_active_board_last_modified_mark_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background'),
        ),
    ]
