# Generated by Django 4.1.3 on 2022-11-29 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0016_alter_board_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='space',
        ),
        migrations.AddField(
            model_name='favorite',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorite', to='boards.board'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Archiwe',
        ),
    ]
