# Generated by Django 4.1.3 on 2022-12-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_changed',
            field=models.DateTimeField(null=True),
        ),
    ]
