# Generated by Django 4.1.3 on 2022-12-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0019_board_last_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.AlterField(
            model_name='card',
            name='date_of_end',
            field=models.DateTimeField(),
        ),
    ]
