# Generated by Django 4.1.3 on 2022-12-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0021_board_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='members',
        ),
        migrations.AlterField(
            model_name='card',
            name='date_of_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
