# Generated by Django 4.1.3 on 2022-12-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0022_remove_card_members_alter_card_date_of_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='boards.board'),
        ),
        migrations.AlterField(
            model_name='member',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='boards.board'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LastSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_time', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
