# Generated by Django 4.1.3 on 2022-12-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0023_remove_board_members_alter_favorite_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='boards.board'),
        ),
    ]
