# Generated by Django 4.1.3 on 2022-12-06 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0024_alter_member_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='boards.board'),
        ),
    ]
