# Generated by Django 4.1.3 on 2022-12-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0025_alter_member_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
